#!/bin/bash
# Quick APK Build Script

echo "======================================"
echo "   PYQverse APK Build Helper"
echo "======================================"
echo ""

echo "📱 APK कैसे बनाएं?"
echo ""
echo "========== विधि 1: Android Studio (आसान) =========="
echo ""
echo "Step 1: Android Studio Install करें"
echo "  → https://developer.android.com/studio"
echo ""
echo "Step 2: Project Setup"
echo "  cd /path/to/pyqverse"
echo "  yarn install"
echo "  yarn build"
echo "  yarn android:sync"
echo ""
echo "Step 3: Android Studio में खोलें"
echo "  → Open: pyqverse/android folder"
echo "  → Wait for Gradle sync"
echo ""
echo "Step 4: Build APK"
echo "  → Build Menu → Build Bundle/APK → Build APK"
echo "  → Wait 2-5 minutes"
echo "  → APK: android/app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "========== विधि 2: Command Line (Fast) =========="
echo ""
echo "Debug APK (Testing):"
echo "  cd android"
echo "  ./gradlew assembleDebug"
echo "  → Output: app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "Release APK (Play Store):"
echo "  cd android"
echo "  ./gradlew assembleRelease"
echo "  → Output: app/build/outputs/apk/release/app-release.apk"
echo ""
echo "========== Play Store Upload =========="
echo ""
echo "Step 1: Signing Key बनाएं"
echo "  keytool -genkey -v -keystore pyqverse-release-key.jks \\"
echo "    -keyalg RSA -keysize 2048 -validity 10000 -alias pyqverse"
echo ""
echo "Step 2: gradle.properties में config करें"
echo "  PYQVERSE_RELEASE_STORE_FILE=pyqverse-release-key.jks"
echo "  PYQVERSE_RELEASE_KEY_ALIAS=pyqverse"
echo "  PYQVERSE_RELEASE_STORE_PASSWORD=YOUR_PASSWORD"
echo "  PYQVERSE_RELEASE_KEY_PASSWORD=YOUR_PASSWORD"
echo ""
echo "Step 3: Signed APK build करें"
echo "  cd android"
echo "  ./gradlew assembleRelease"
echo ""
echo "Step 4: Play Console पर upload करें"
echo "  → https://play.google.com/console"
echo "  → Create app → Upload APK"
echo ""
echo "========== Files Needed =========="
echo ""
echo "✅ Build करने के लिए:"
echo "  • Android Studio"
echo "  • Java JDK 17+"
echo "  • Project files"
echo ""
echo "✅ Play Store के लिए:"
echo "  • Signed release APK"
echo "  • App icon (512x512)"
echo "  • Screenshots (8 images, 1080x1920)"
echo "  • Feature graphic (1024x500)"
echo "  • Store description"
echo "  • Privacy policy"
echo ""
echo "========== Quick Links =========="
echo ""
echo "Android Studio: https://developer.android.com/studio"
echo "Play Console: https://play.google.com/console"
echo "Complete Guide: /app/APK_BUILD_GUIDE.md"
echo ""
echo "======================================"
echo ""
