

export enum ExamType {
  UPSC = 'UPSC',
  SSC_CGL = 'SSC CGL',
  JEE_MAINS = 'JEE Mains',
  NEET = 'NEET',
  BANKING = 'Banking',
  RAILWAYS = 'Railways',
  GATE = 'GATE'
}

export enum QuestionSource {
  PYQ_AI = 'PYQ_AI', // Generated by AI simulating PYQs
  USER = 'USER'      // Uploaded by user for revision
}

export enum QuestionType {
  MCQ = 'MCQ',
  SHORT_ANSWER = 'SHORT_ANSWER',
  LONG_ANSWER = 'LONG_ANSWER',
  NUMERICAL = 'NUMERICAL',
  VIVA = 'VIVA'
}

export interface Question {
  id: string;
  text: string;
  textHindi?: string; // Added for bilingual support
  options: string[];
  optionsHindi?: string[]; // Added for bilingual support
  correctIndex: number;
  explanation?: string;
  explanationHindi?: string; // Added for bilingual support
  source: QuestionSource;
  examType: ExamType; // e.g., 'SSC CGL'
  subject?: string;
  createdAt: number;
  tags?: string[];
  // New fields for Full Paper
  type?: QuestionType;
  marks?: number;
  answer?: string; // Model answer for non-MCQ
  answerHindi?: string; // Added for bilingual support
  userAnswer?: string; // Student's answer during mock test
}

export interface PaperSection {
  id: string;
  title: string;
  instructions: string;
  questions: Question[];
  marksPerQuestion: number;
}

export interface QuestionPaper {
  id: string;
  title: string;
  examType: ExamType;
  subject: string;
  difficulty: string;
  totalMarks: number;
  durationMinutes: number;
  sections: PaperSection[];
  createdAt: number;
}

export interface ExamResult {
  id: string;
  examType: ExamType;
  paperTitle: string;
  score: number;
  totalMarks: number;
  accuracy: number;
  date: number; // Timestamp
  timeTakenSeconds: number;
  topicAnalysis: Record<string, { correct: number; total: number }>; // e.g. {'Algebra': {correct: 2, total: 5}}
}

export interface UserStats {
  totalAttempted: number;
  totalCorrect: number;
  streakCurrent: number;
  streakMax: number;
  lastActiveDate: string; // ISO date string YYYY-MM-DD
  subjectPerformance: Record<string, { correct: number; total: number }>;
  examPerformance?: Record<string, {
    totalAttempted: number;
    totalCorrect: number;
    subjectPerformance: Record<string, { correct: number; total: number }>;
  }>;
}

export interface User {
  id: string;
  name: string;
  email: string;
  photoURL?: string;
  educationLevel?: string;
  targetYear?: string;
  dailyGoal?: number;
  // New profile fields
  mobile?: string;
  currentClass?: string;
  address?: string;
  state?: string;
  pincode?: string;
}

export type ViewState = 'login' | 'signup' | 'forgotPassword' | 'onboarding' | 'tutorial' | 'dashboard' | 'practice' | 'upload' | 'stats' | 'profile' | 'paperGenerator' | 'paperView';

export interface AppState {
  view: ViewState;
  selectedExam: ExamType | null;
  stats: UserStats;
  user: User | null;
  showTimer: boolean;
  generatedPaper?: QuestionPaper | null;
  darkMode: boolean;
  language: 'en' | 'hi';
  theme: string;
}