
export enum ExamType {
  UPSC = 'UPSC',
  SSC_CGL = 'SSC CGL',
  SSC_CHSL = 'SSC CHSL',
  SSC_MTS = 'SSC MTS',
  JEE_MAINS = 'JEE Mains',
  NEET = 'NEET',
  BANKING = 'Banking',
  RAILWAYS = 'Railways',
  RRB_NTPC = 'RRB NTPC',
  GATE = 'GATE',
  NDA = 'NDA',
  CDS = 'CDS',
  STATE_PSC = 'State PSC',
  TEACHING_CTET = 'Teaching (CTET)',
  POLICE_CONSTABLE = 'Police Constable'
}

export enum QuestionSource {
  PYQ_AI = 'PYQ_AI', // Generated by AI simulating PYQs
  USER = 'USER',      // Uploaded by user for revision
  OFFICIAL = 'OFFICIAL' // Uploaded by Admin
}

export enum QuestionType {
  MCQ = 'MCQ',
  SHORT_ANSWER = 'SHORT_ANSWER',
  LONG_ANSWER = 'LONG_ANSWER',
  NUMERICAL = 'NUMERICAL',
  VIVA = 'VIVA'
}

export interface Question {
  id: string;
  text: string;
  textHindi?: string;
  options: string[];
  optionsHindi?: string[];
  correctIndex: number;
  explanation?: string;
  explanationHindi?: string;
  source: QuestionSource;
  examType: ExamType;
  subject?: string;
  createdAt: number;
  tags?: string[];
  // New fields
  type?: QuestionType;
  marks?: number;
  answer?: string;
  answerHindi?: string;
  userAnswer?: string;
  isBookmarked?: boolean;
  // Admin fields
  pyqYear?: number;
  moderationStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';
}

export interface NewsItem {
  id: string;
  headline: string;
  headlineHindi?: string;
  summary: string;
  summaryHindi?: string;
  category: string;
  date: string;
  tags: string[];
  isOfficial?: boolean; // True if uploaded by Admin
}

export interface PaperSection {
  id: string;
  title: string;
  instructions: string;
  questions: Question[];
  marksPerQuestion: number;
}

export interface QuestionPaper {
  id: string;
  title: string;
  examType: ExamType;
  subject: string;
  difficulty: string;
  totalMarks: number;
  durationMinutes: number;
  sections: PaperSection[];
  createdAt: number;
}

export interface ExamResult {
  id: string;
  examType: ExamType;
  paperTitle: string;
  score: number;
  totalMarks: number;
  accuracy: number;
  date: number;
  timeTakenSeconds: number;
  topicAnalysis: Record<string, { correct: number; total: number }>;
}

export interface UserStats {
  totalAttempted: number;
  totalCorrect: number;
  streakCurrent: number;
  streakMax: number;
  lastActiveDate: string;
  subjectPerformance: Record<string, { correct: number; total: number }>;
  examPerformance?: Record<string, {
    totalAttempted: number;
    totalCorrect: number;
    subjectPerformance: Record<string, { correct: number; total: number }>;
  }>;
}

export interface User {
  id: string;
  name: string;
  email: string;
  photoURL?: string | null;
  educationLevel?: string;
  targetYear?: string;
  dailyGoal?: number;
  mobile?: string;
  currentClass?: string;
  address?: string;
  state?: string;
  pincode?: string;
  isPro?: boolean;
  isAdmin?: boolean; // Admin Flag
}

export interface SubscriptionPlan {
  id: string;
  name: string;
  price: number;
  currency: string;
  duration: string;
  features: string[];
  recommended?: boolean;
}

export interface LeaderboardEntry {
  id: string;
  rank: number;
  name: string;
  exam: string;
  score: number; // XP or Total Correct
  isCurrentUser: boolean;
}

export type ViewState = 'login' | 'signup' | 'forgotPassword' | 'onboarding' | 'tutorial' | 'dashboard' | 'practice' | 'upload' | 'stats' | 'profile' | 'paperGenerator' | 'paperView' | 'bookmarks' | 'admin' | 'downloads' | 'analytics' | 'leaderboard' | 'news' | 'pyqLibrary';

export interface AppState {
  view: ViewState;
  selectedExam: ExamType | null;
  stats: UserStats;
  user: User | null;
  showTimer: boolean;
  generatedPaper?: QuestionPaper | null;
  darkMode: boolean;
  language: 'en' | 'hi';
  theme: string;
  qotd?: Question | null;
  newsFeed?: NewsItem[];
}
