import React from 'react';
import { Button } from './Button';

interface TermsOfServiceProps {
  onBack: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 p-6 sm:p-12 font-sans animate-fade-in">
      <div className="max-w-4xl mx-auto bg-white dark:bg-slate-800 rounded-3xl shadow-xl p-8 border border-slate-200 dark:border-slate-700">
        <div className="flex justify-between items-center mb-8">
          <h1 className="text-3xl font-bold font-display text-brand-purple">Terms of Service</h1>
          <Button onClick={onBack} variant="secondary" size="sm">Back to App</Button>
        </div>

        <div className="prose dark:prose-invert max-w-none space-y-6">
          <p className="text-sm text-slate-500">Last Updated: October 2023</p>

          <section>
            <h2 className="text-xl font-bold mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing and using PYQverse, you accept and agree to be bound by the terms and provision of this agreement. 
              If you do not agree to abide by these terms, please do not use this service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-2">2. Usage Rights</h2>
            <p>
              You are granted a limited, non-exclusive, non-transferable license to access the PYQverse app for personal, non-commercial educational use.
              You agree not to copy, modify, or distribute the app's content or source code.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-2">3. AI Content Disclaimer</h2>
            <p>
              The questions and explanations generated by our AI engine are for practice purposes only. While we strive for accuracy, PYQverse cannot guarantee 
              that all generated content is 100% error-free. Users should verify critical information from official textbooks.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-2">4. User Account</h2>
            <p>
              You are responsible for maintaining the security of your account credentials. PYQverse is not liable for any loss or damage arising from your failure 
              to comply with this security obligation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-2">5. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at our sole discretion, without notice, for conduct that we believe violates these Terms of Service 
              or is harmful to other users of the app.
            </p>
          </section>
        </div>

        <div className="mt-8 pt-6 border-t border-slate-200 dark:border-slate-700 text-center">
           <p className="text-xs text-slate-500">© 2025 PYQverse. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
};