
import React, { useState } from 'react';
import { Button } from './Button';

interface TutorialProps {
  onComplete: () => void;
}

export const Tutorial: React.FC<TutorialProps> = ({ onComplete }) => {
  const [step, setStep] = useState(0);

  const steps = [
    {
      title: "AI-Powered Practice",
      desc: "Practice with unlimited questions generated by AI based on real exam patterns.",
      icon: (
        <div className="w-24 h-24 bg-brand-100 rounded-full flex items-center justify-center text-5xl mb-6 shadow-inner text-brand-600 animate-float">
          🤖
        </div>
      )
    },
    {
      title: "Your Personal Vault",
      desc: "Found a tough question? Upload it here. We'll mix it into your practice sessions for smart revision.",
      icon: (
        <div className="w-24 h-24 bg-purple-100 rounded-full flex items-center justify-center text-5xl mb-6 shadow-inner text-purple-600 animate-float">
          📝
        </div>
      )
    },
    {
      title: "Track Your Growth",
      desc: "Visualize your progress subject-wise and maintain your daily streak to master your preparation.",
      icon: (
        <div className="w-24 h-24 bg-green-100 rounded-full flex items-center justify-center text-5xl mb-6 shadow-inner text-green-600 animate-float">
          📈
        </div>
      )
    }
  ];

  const handleNext = () => {
    if (step < steps.length - 1) {
      setStep(step + 1);
    } else {
      onComplete();
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
      <div className="bg-white max-w-md w-full rounded-3xl shadow-2xl p-8 flex flex-col items-center text-center animate-fade-in border border-slate-100 relative overflow-hidden">
        
        {/* Background decoration */}
        <div className="absolute -top-10 -right-10 w-32 h-32 bg-brand-50 rounded-full blur-3xl pointer-events-none"></div>
        <div className="absolute -bottom-10 -left-10 w-32 h-32 bg-purple-50 rounded-full blur-3xl pointer-events-none"></div>

        <div className="flex-1 flex flex-col items-center justify-center min-h-[320px] relative z-10">
          {steps[step].icon}
          <h2 className="text-2xl font-bold text-slate-800 mb-3 animate-fade-in" key={`title-${step}`}>{steps[step].title}</h2>
          <p className="text-slate-500 leading-relaxed animate-fade-in" key={`desc-${step}`}>{steps[step].desc}</p>
        </div>

        <div className="w-full mt-8 space-y-6 relative z-10">
          <div className="flex justify-center gap-2">
            {steps.map((_, idx) => (
              <div 
                key={idx} 
                className={`h-2 rounded-full transition-all duration-300 ${idx === step ? 'w-8 bg-brand-600' : 'w-2 bg-slate-200'}`}
              />
            ))}
          </div>

          <Button onClick={handleNext} className="w-full py-3 shadow-lg shadow-brand-200">
            {step === steps.length - 1 ? "Get Started" : "Next"}
          </Button>

          {step < steps.length - 1 && (
            <button 
              onClick={onComplete}
              className="text-sm text-slate-400 hover:text-slate-600 font-medium transition-colors"
            >
              Skip Tutorial
            </button>
          )}
        </div>
      </div>
    </div>
  );
};
